#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.

# Functions

def viralAdvertising(n):
    # Write your code here
    shared = 5
    # liked = math.floor(shared/2)
    cumulative = 0
    
    for _ in range(n):
        
        
        liked = math.floor(shared/2)
        cumulative += liked
        shared = liked * 3
        
        print(shared)
        print(liked)
    
    return cumulative

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()

