#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    highScore = scores[0]
    lowScore = scores[0]
    answer = [0, 0]
    
    for score in scores:
      
        if score > highScore:
            answer[0] += 1
            highScore = score
        elif score < lowScore:
            answer[1] += 1
            lowScore = score
    print(highScore, lowScore)
    return answer

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
